### ISSUE TITLE
Change linter rules for config/database.yml

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api-template#33]
The linter hates this file.

**Comment by raq929** [comment]
Also auto-generated rails files, like schema.

So, adding something like this to `rubocop.yml`

```
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'config/database.yml'
```

**Comment by raq929** [comment]
@gaand mentions we shouldn't turn off all linting, just the linting that's relevant to these files.

**Comment by raq929** [comment]
So more like:
```ruby
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/models/*'
    - 'app/serializers/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'config/database.yml'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
```

**Comment by gaand** [comment]
I ended up here, which may still exclude too many files

```yaml
Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/models/*'
    - 'app/serializers/*'
    - 'db/migrate/**'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/database.yml'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
```
